name: space_explorer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  connectivity_plus: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/iconoAPP.png
    - lib/assets/splash1.png
    - lib/assets/splash2.png
