name: space_explorer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  connectivity_plus: ^5.0.2
  share_plus: ^7.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5


flutter:
  uses-material-design: true
  assets:
    - lib/assets/iconoAPP.png
    - lib/assets/splash1.png
    - lib/assets/splash2.png

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "lib/assets/splash2.png"
  image_path: "lib/assets/splash2.png"

flutter_native_splash:
  color: "#000000"
  image: lib/assets/iconoAPP.png
  android: true
  ios: true